### ISSUE TITLE
marketing: add repository to "awesome-for-non-programmers"

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-dot-io#16]
## Awesome-For-Non-Programmers

Would love to add this repository to the [`awesome-for-non-programmers`](https://github.com/szabgab/awesome-for-non-programmers) repository for non programmers to learn about open source opportunities that don't require a technical background. 

Within the Legesher project, there are a lot of opportunities for people of all backgrounds to contribute the skills they either want to grow in or give back. With a strong emphasis on written language translation, individuals who are bilingual have a great space to contribute. Individuals who want to grow in community development, marketing, writing impactful pieces of insight, or just want to learn more about the tech world have ample amounts of opportunities here as well! 

Below are some opportunities for non-programmers:
- `Opportunity: Copy`: for those who want to work on any thing copy-related  
- `Opportunity: Design`: for those who want to work on any thing design-related  
- `Opportunity: Marketing`: for those who want to work on any thing marketing-related  
- `Opportunity: User Experience`: for those who want to work on any thing ux-related  
- `Opportunity: Data`: for those who want to work on any thing data-related  
- `Opportunity: Legal`: for those who want to work on any thing legal-related  
- `Opportunity: Great First Issue`: for those who don't know where to start  
- `Opportunity: Technical Beginner`: for those who have little to no technical experience

More details can be found in their pull request template.

**Comment by Navneet78** [comment]
Hey @madiedgar I want to do this it would be my first PR.

**Comment by madiedgar** [comment]
Awesome @Navneet78! 🎉 Let's do it!! I'll assign you to this issue and we can walk through it together! 😄

**Comment by madiedgar** [comment]
Awesome job on [this](https://github.com/szabgab/awesome-for-non-programmers/pull/19) @Navneet78!

**Comment by Navneet78** [comment]
Thanks @madiedgar what next?

**Comment by madiedgar** [comment]
@Navneet78 I'm working on adding some more issues to this repository and the others within this organization. Are there any specific areas you would like to work in / learn / grow? As I'm creating them, I can tag you in the issues that I feel would be aligned with how you're wanting to contribute!

**Comment by Navneet78** [comment]
Yes I am having experience in python, javascript I want to learn more and grow in that areas.

**Comment by madiedgar** [comment]
Hey @naveet78 thank you for contributing to this repository! 🎉🎉🎉 ❤️ THANK YOU THANK YOU THANK YOU ❤️ We'd love to celebrate you and your contribution to the community. Let us say "Thank You" again, by sending you a [special gift](https://madi357705.typeform.com/to/wzub4R)!

We couldn't thank you enough for your contribution. We hope you continue sharing your gifts and knowledge with not just us, but with the world around you.😍
