### ISSUE TITLE
Website tweak.

### ISSUE THREAD

**Issue by Stoozy** [legesher/legesher-dot-io#24]
So I had a look at the website and I felt that there was too much white space. Especially at the 4 features section. I did a fix and wonder if you guys would like me to go through with this on the actual website. It's understandable if you don't.

![brandedbg](https://user-images.githubusercontent.com/16365016/66262238-6d8e2700-e7aa-11e9-815d-f8409ac5984b.jpg)

**Comment by madiedgar** [comment]
Thank you so much @Stoozy for this! I really appreciate the thought behind it all 😉. We're drafting up designs for the next version of the website, and would love your thoughts on it as we roll it out and how we can best utilize extra whitespace! 

For right now, though, we seemed to have cut out some of the svg images on the landing page. Could you lead this effort in figuring out why it's cutting the colors off? 
<img width="1251" alt="Screen Shot 2019-10-25 at 3 25 37 PM" src="https://user-images.githubusercontent.com/7844510/67598623-f827cd80-f73b-11e9-8764-e30aa2095b88.png">

**Comment by shahkv95** [comment]
@madiedgar I believe adding cards (effect) to the four features will make it appear better with a proper shadow effect of the card.
Would like to know what you think regarding the same.

**Comment by madiedgar** [comment]
@shahkv95, I'm not familiar with the "cards" effect, but I'd be down to test it out! For reference, this is what it used to look like at [this point](https://github.com/legesher/legesher-dot-io/tree/7144acb17f04ee5417cd9482b07242f00c116028)🙈. 

<img width="1129" alt="Screen Shot 2019-10-25 at 5 06 03 PM" src="https://user-images.githubusercontent.com/7844510/67604537-ce75a300-f749-11e9-82b9-de831f71def1.png">

**Comment by Stoozy** [comment]
Sorry for being late and all but my live view doesn't show the SVGs cutting off.

![image](https://user-images.githubusercontent.com/16365016/69112078-716dc400-0a4d-11ea-8da7-c2e3aa2c739b.png)
