### ISSUE TITLE
Text rendering issue 

### ISSUE THREAD

**Issue by MythreyaK** [legesher/legesher-dot-io#26]
The glyph here cannot be rendered. Works in Chrome but not Firefox.

![image](https://user-images.githubusercontent.com/26112391/66411386-500ec680-ea11-11e9-9ba1-9d625e435840.png)

Page :[lets-get-it-started](https://legesher.readme.io/docs/lets-get-it-started)

**Comment by madiedgar** [comment]
Oooh thanks for finding this bug 🐛! I'm going to change all the emojis to be the code `: emoji_key :` instead of copying the emojis. Hopefully that will work in both chrome and firefox!

**Comment by MythreyaK** [comment]
My pleasure!
I tried to make a PR, couldn't find the relevant file. If you think it's okay, could I try a PR?

**Comment by MythreyaK** [comment]
I've been assigned, but the issue has been closed. Do I work on it?

**Comment by madiedgar** [comment]
Sorry @MythreyaK, I use the assignment tool to keep track of contributions and I missed this one! You're all good 👍

**Comment by MythreyaK** [comment]
It's okay! Can confirm it's fixed!
