### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-dot-io#28]
Add a `CONTRIBUTING.md` file in the root of the repository that contains this content:

```md
See the [Legesher contributing guide](https://github.com/legesher/legesher/blob/master/CONTRIBUTING.md)
```

Simple enough 👍 Please ask to be assigned to this issue so we don't have duplicates 😄

**Comment by fedebabrauskas** [comment]
Hi there,

Can I be asigned to this issue?

Thank you.

**Comment by madiedgar** [comment]
Absolutely @fedebabrauskas! I'll assign you to it!
