### ISSUE TITLE
Update README link to LANGUAGE_CONVENTIONS

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-dot-io#31]
## Update link in README

In [this section of the README file](https://github.com/legesher/legesher-dot-io#contributing), it links to a file in the `legesher` repository that is no longer there. Here is the [link to the new file](https://github.com/legesher/legesher/blob/master/LANGUAGE_CONVENTIONS.md). 

`https://github.com/legesher/legesher/blob/master/LANGUAGE_CONVENTIONS.md`

**Comment by joaoluizn** [comment]
Working on this.

**Comment by irfansener** [comment]
I fixed this. Can you check pr ?

**Comment by madiedgar** [comment]
Awesome, thank you @irfansener!
