### ISSUE TITLE
Update Home Page Content

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-dot-io#33]
## Home Page Content Clean Up
There are a couple of typo's in the home page that need to be cleaned up! 

- [ ] In the "Stay In The Know" section at the bottom of the page, `welcomed` is misspelled. 
- [ ] In the "Develop" section, change the first sentence: `Innovation and creativity should never be lost in translation, that’s why we created Legesher!` to `Innovation, creativity, and collaboration should never be lost in translation, that’s why we created Legesher!`

**Comment by shahkv95** [comment]
@madiedgar Could I work on this issue?

**Comment by madiedgar** [comment]
Amazing!! THank you @shahkv95

**Comment by shahkv95** [comment]
I have created the PR @madiedgar . Please accept it .
Thank you.

**Comment by Yutyo** [comment]
I am working too.

**Comment by shahkv95** [comment]
I have created one more PR @madiedgar . I have made few more standard correction. 
Please accept it  and merge the PR.
Thank you.

**Comment by Yutyo** [comment]
Can you accept my pull request too?

**Comment by Yutyo** [comment]
Hi, why you have labeled my pull request as invalid?

**Comment by madiedgar** [comment]
Hey @Yutyo 👋, part of creating a quality pull request is that the contribution pushes the project forward. I've been receiving multiple pull requests that aren't aligned with the purpose of the project so the best way to make sure your contribution serves us all is to first create an issue detailing the proposed changes. If accepted, then you can proceed to completing the pull request. Hope this helps clarify!

**Comment by BlackSou** [comment]
I h made few more standard correction.
Please accept it and merge the PR.
Thank you!
@madiedgar

**Comment by madiedgar** [comment]
Closing this issue as it was resolved in multiple pr's 🎉
