### ISSUE TITLE
Subscribe form is triggered for both Header and Footer on a single submit event

### ISSUE THREAD

**Issue by ARUNMOHANRAJ471** [legesher/legesher-dot-io#58]
**Describe the bug**
Whenever we click on the _Get early access_ button(both in the header and footer), it triggers both the registerHeader, registerFooter functions in the mailchimp.js

**To Reproduce**
1. Go to https://legesher.io/
2. Click on Get Early access without filling any data
3. You should see error message in both header and footer email input fields

**Expected behavior**
On click of the button, based on header/footer only a single request has to be made for validation and subscription to mailchimp.

**Screenshots**
![image](https://user-images.githubusercontent.com/24914964/95044305-b699f380-06fc-11eb-811f-3144df98bb7d.png)
![image](https://user-images.githubusercontent.com/24914964/95044320-c1ed1f00-06fc-11eb-8f54-5b497d9cb8b1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 85.0.4183.121

 
 **Possible Solution**
In the ajax-mailchimp.js file, the click event binded for submit should be binded to an document id. I have done the changes in [this commit](https://github.com/ARUNMOHANRAJ471/legesher-dot-io/commit/5d84166407f5144bda48e861fb149b7a09e7ad97) in the forked repo. I can raise a PR once the bug is accepted.

**Comment by roycebradley** [comment]
@ARUNMOHANRAJ471 Let me know if there is anything I can do to help!

**Comment by madiedgar** [comment]
thanks so much for looking into this @ARUNMOHANRAJ471. This is the same problem described in #38, so I would love to resolve this. Looking into your PR now. 👍

**Comment by madiedgar** [comment]
Thanks for your help @ARUNMOHANRAJ471 👍 if either you or @roycebradley would like to help with #38 that would be extremely helpful.

**Comment by ARUNMOHANRAJ471** [comment]
Sure @madiedgar I would like to take up that. I did an analysis on that too. Will raise a PR sooner. Could you pls point me to the docs for reference for this mail chimp api. Because I want to confirm on the possible responses we get from this api. Thanks!

**Comment by madiedgar** [comment]
Amazing @ARUNMOHANRAJ471 - Here are some of the resources I've found:
- [Mailchimp Developer Tools Main Site](https://mailchimp.com/developer/)
- [Mailchimp API Reference Docs](https://mailchimp.com/developer/api/marketing/)
