### ISSUE TITLE
bug: svg images are cut off incorrectly on landing page

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-dot-io#61]
**Describe the bug**
The svg images on the home page are cut off in certain places and aren't loading properly. 

**Expected behavior**
This is how it is supposed to be displayed:

![](https://user-images.githubusercontent.com/7844510/67604537-ce75a300-f749-11e9-82b9-de831f71def1.png)

This is how it is currently being displayed for me:

![](https://user-images.githubusercontent.com/7844510/67598623-f827cd80-f73b-11e9-8764-e30aa2095b88.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.7
 - Browser Chrome, Safari & Firefox
 
 **Possible Solution**
@shahkv95 mentioned in #24 about adding cards (effect) to the four features. Open to suggestions.

**Comment by madiedgar** [comment]
Awesome @Abhijay007 , let me know if you have any questions!

**Comment by Abhijay007** [comment]
> @Abhijay007 I got the same issue the work around for now is to copy paste the start command `parcel index.html dreamteam.html` into the terminal and run.

@akshitarora921 thanks, I will try this and get back to you !!

**Comment by TomerPacific** [comment]
@madiedgar - is this still relevant?
