### ISSUE TITLE
content: fix footer link organization

### ISSUE THREAD

**Issue by akshitarora921** [legesher/legesher-dot-io#75]
## '2018-2021 With Madi Co,' is linked but only 'With Madi Co,' should have (Footer)
**Describe the bug**
At Footer, link to https://withmadi.co/ is at the text '2018-2021 With Madi Co'

**To Reproduce**
1. Go to https://legesher.io/
2. Scroll down to the bottom of the page
4. Hover on the text '2018-2021 With Madi Co,'

**Expected behavior**
The link should be only at 'With Madi Co'

**Desktop (please complete the following information):**
 
- OS: Windows
- Browser: Chrome
- Version: 85.0.4183.12

 **Possible Solution**
Anchor tag should be only at 'With Madi Co'

**Additional context**
This project is now it's own entity and no longer under @madiedgar 's personal business - With Madi Co. the footer should now state Legesher Inc. as the company name.

**Comment by madiedgar** [comment]
Thanks for raising this issue @akshitarora921, I will review your PR.
