### ISSUE TITLE
bug: invalid discord invite on home page icon

### ISSUE THREAD

**Issue by Sourabh06** [legesher/legesher-dot-io#79]
**Expired Discord invite link**
The discord button on the official page of [legesher](https://legesher.io/) has an expired discord invite.

**To Reproduce**
1. Go to [Official link](https://legesher.io/)
2. Scroll down to the bottom.
3. Click on discord icon

**Expected behavior**
Users should be able to accept invitation to the shared server.

**Screenshots**

Discord button
![discord-btn](https://user-images.githubusercontent.com/26255201/137451283-35e7a396-11e4-4a98-a43b-723870426cb4.png)

Redirection to expired invite link
![invalid-invite](https://user-images.githubusercontent.com/26255201/137452094-b42924b4-920e-43ac-85a7-decb7c500c2f.png)

**Desktop:**
 - OS: Windows 10(Not OS specific)
 - Browser: Chrome. (Not browser specific)
 - Version: 94.0.4606.81 (Official Build) (64-bit)

**Smartphone:**
 - Device: Asus X01BDA(Not device specific)
 - OS: Android 11(Not OS specific)
 - Browser:  Brave (Not browser specific)
 - Version: 1.30.87
 
 **Possible Solution**
1. Set the invite to never expire. Make sure to verify the users before allowing them to join.
OR
2. share a form/link that will allow users to join the discord server. You can personally mail the users with an active invite link.

**For PRs**
How can we raise a PR for this issue?
Non-sequitr, you can add hacktoberfest label to this issue :)

**Comment by madiedgar** [comment]
Thanks for finding this bug @Sourabh06! The correct invite code is https://discord.gg/DkVjVDP. I assigned you to the issue if you would like to complete it for Hacktoberfest credit. Let me know if I can help you in any way!
