### ISSUE TITLE
bug: email submission form not accepting entries

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-dot-io#80]
Thank you to @sanjay-kv for raising this issue ([#235](https://github.com/legesher/legesher-translations/issues/235))

**Describe the bug**
There are two Email forms on the front page of Legesher.io to signup for early access. Those are not working, once the user enters the value it returns please enter a value rather than giving confirmation or redirecting.

**To Reproduce**
1. Go to 'https://legesher.io/'
2. Click on 'Get Early access program Email form '
3. Scroll down to 'Email box and enter the email'

**Expected behavior**
Either redirecting the customer saying the early access is full and whats the update or release date is and make sure to give a hook to bring them back later (email list) or show successful mail for the beta version.

**Screenshots**
I had to change the required fields for the email inpt from email only, to first name and email. This is the bare look from mailchimp, but it needs to incorporate the styles already present in the legesher.io website. 
<img width="728" alt="Screen Shot 2021-10-15 at 5 38 25 AM" src="https://user-images.githubusercontent.com/7844510/137466959-3c77d95f-38e7-4f14-9e07-a2cc7c4daeba.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11
 - Browser [chrome]
 - Version [Version 94.0.4606.71 (Official Build) (64-bit)]
 
 **Possible Solution**
I found this article bit helpful in collecting emails using python
https://realpython.com/handling-email-confirmation-in-flask/

**Additional context**
@madiedgar : I've recently made some changes to how the emails are serviced / naming conventions. These changes I believe are the reason for some of the errors you currently see on the site. Below is the code for the new email campaign, particularly the api endpoint :  https://legesher.us19.list-manage.com/subscribe/post?u=6f4999131288a850ad71d6e54&amp;id=c75cd847f2

```
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://legesher.us19.list-manage.com/subscribe/post?u=6f4999131288a850ad71d6e54&amp;id=c75cd847f2" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<p><a href="https://us19.campaign-archive.com/home/?u=6f4999131288a850ad71d6e54&id=c75cd847f2" title="View previous campaigns">View previous campaigns.</a></p>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_6f4999131288a850ad71d6e54_c75cd847f2" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[6]='GITHUBUSER';ftypes[6]='text';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[0]='EMAIL';ftypes[0]='email';fnames[3]='ADDRESS';ftypes[3]='address';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
```

**Comment by madiedgar** [comment]
Hey @sanjay-kv 👋, you can work on that issue here!

**Comment by akshitarora921** [comment]
@madiedgar can you assign this to me.

**Comment by akshitarora921** [comment]
@madiedgar also Is there any API reference that I can refer to?

**Comment by akshitarora921** [comment]
@madiedgar I think we need to use this API https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/
